# frozen_string_literal: true

Vagrant.configure('2') do |config|
  ['ubuntu/jammy64', 'debian/bullseye64'].each do |box|
    vm_name = box.split('/').last

    config.vm.define(vm_name) do |machine|
      machine.vm.box = box
      machine.vm.provision 'ansible' do |ansible|
        ansible.playbook = 'playbook.yml'
        ansible.galaxy_roles_path = '../..'
        ansible.compatibility_mode = '2.0'
      end

      # config.vm.provision 'shell', path: 'scripts/run-tests', privileged: false
    end
  end
end
